-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 15:02:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lostandfound
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lostandfound
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lostandfound` DEFAULT CHARACTER SET utf8 ;
USE `lostandfound` ;

-- -----------------------------------------------------
-- Table `lostandfound`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lostandfound`.`items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `found_by` VARCHAR(60) NOT NULL,
  `location_bf` VARCHAR(60) NOT NULL,
  `location_now` VARCHAR(60) NOT NULL,
  `picture` VARCHAR(128) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `collected` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
